version: '3'
services:
  laravel:
    build:
      context: .
    ports:
      - 80:80
    networks:
      - laravel-app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      - laravel-app
networks:
  laravel-app:
    driver: bridge
volumes:
    mysql-volume:
      driver: local